# Runnable at https://developer.github.com/v4/explorer/
# Not scripted because I cannot be bothered with authentication
# Save output json into gh_repos.json
# then run the following jq command
#
#  $ jq -r ".data.search.edges[].node.url" < gh_repos.json | sort -f > repo_list

query {
  search(type: REPOSITORY, query: "topic:kiss-repo", first: 100) {
    edges {
      node {
        __typename
        ... on Repository {
          url
        }
      }
    }
  }
}

