name: preview

on: [ pull_request ]

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: create preview
        run: |
          echo generating a preview for ${GITHUB_HEAD_REF}
          mkdir -p docs/preview
          cp -f docs/index.html docs/preview/${GITHUB_HEAD_REF}.html
          git fetch origin main
          git checkout -b main origin/main
          git add docs/preview/${GITHUB_HEAD_REF}.html
          git commit --message "preview for ${GITHUB_HEAD_REF}"
          git push origin HEAD:main
          echo preview generated at https://jedahan.com/kiss-find/preview/${GITHUB_HEAD_REF}.html
